// Regenerates src/lib/version.ts from package.json so the published package
// reports its real name/version in userAgent and sdkMetadata. Runs as part of
// the `package` script, before svelte-package.
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf-8'));

writeFileSync(
	new URL('../src/lib/version.ts', import.meta.url),
	`// Generated by scripts/sync-version.js — do not edit.
export const PACKAGE_NAME = '${pkg.name}';
export const PACKAGE_VERSION = '${pkg.version}';
`
);
